#!/bin/sh -e

if [ $# -lt 2 ]; then
  echo "MMonit Host Status for CLI"
  echo "Usage:"
  echo "$0 group action"
  echo "   group:[GROUP or ALL]"
  echo "   active:[active|ignored|inactive]"
  exit 1
fi

MMONIT="$MMONIT_HOST"
USERNAME=$MMONIT_USERNAME
PASSWORD=$MMONIT_PASSWORD
GROUP=$1
STATUS=$2

case $STATUS in
  inactive ) ACTION=1 ;;
  ignored  ) ACTION=2 ;;
  active   ) ACTION=0 ;;
esac

[ -d ~/.mmonit ] || mkdir -m 0700 ~/.mmonit

curl -s -c ~/.mmonit/cookie \
  https:/$MMONIT/index.csp \
  >> /dev/null

curl -s -b ~/.mmonit/cookie \
  -d z_username=$USERNAME \
  -d z_password=$PASSWORD \
  -d z_csrf_protection=off \
  https://$MMONIT/z_security_check \
  >> /dev/null

if [ $GROUP = "ALL" ]; then
  HOSTS=$( \
    curl -s -b ~/.mmonit/cookie \
    "https://$MMONIT/admin/groups/list" \
    | jq -r ".groups[] | .hosts[]"\
    )
else
  HOSTS=$( \
    curl -s -b ~/.mmonit/cookie \
    "https://$MMONIT/admin/groups/list" \
    | jq -r ".groups[] | select(.name == \"$GROUP\").hosts[]"\
    )
fi

printf "$GROUP Hosts Change Status ${STATUS} Requesting..."

jsonfile=`mktemp mmonit.XXXXXX`
trap "[ -f $jsonfile ] && rm -f $jsonfile" EXIT

for i in $HOSTS; do
  curl -s -b ~/.mmonit/cookie -o $jsonfile "https://$MMONIT/admin/hosts/get?id=$i"
  hostname=$(jq -r ".hostname" $jsonfile)
  monituser=$(jq -r ".monituser" $jsonfile)
  monitpassword=$(jq -r ".monitpassword" $jsonfile)
  ipaddrout=$(jq -r ".ipaddrout" $jsonfile)
  portout=$(jq -r ".portout" $jsonfile)
  keepname=$(jq -r ".keepname" $jsonfile)
  skew=$(jq -r ".skew" $jsonfile)
  description=$(jq -r ".description" $jsonfile)
  curl -s -b ~/.mmonit/cookie \
    -d id=$i \
    -d monituser="$monituser" \
    -d monitpassword="$monitpassword" \
    -d hostname="$hostname" \
    -d keepname="1" \
    -d ipaddrout="$ipaddrout" \
    -d portout="$portout" \
    -d keepname="$keepname" \
    -d status="$ACTION" \
    -d skew="$skew" \
    -d description="$description" \
    https://$MMONIT/admin/hosts/update
    printf .
done

printf "\\033[1;32mSuccess!\\033[0;39m"
